name: "Amazon Package Tracker"
description: "Track your Amazon packages in Home Assistant"
version: "0.1.0"
slug: "amazon_tracker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
panel_icon: "mdi:package-variant"
ports:
  8123/tcp: 8123
options:
  email: ""
  password: ""
schema:
  email: str
  password: str
image: "huskynarr/{arch}-addon-amazon-tracker" 