name: HACS Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: HACS Release
        uses: hacs/action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 